version: '3'
services:
  api:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: app:latest
    ports:
      - 8080:80
    volumes:
      - .:/var/www
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: bp
      DB_USERNAME: bpuser
      DB_PASSWORD: bppassword
    expose:
      - 8080
  mysql:
    image: mysql:5.7
    container_name: database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bp
      MYSQL_USER: bpuser
      MYSQL_PASSWORD: bppassword
      MYSQL_ROOT_PASSWORD: password
